name: CI/CD for food_order frontend project

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Explicitly set to Node 20 to avoid warnings

      - name: Install dependencies
        run: npm install
        # Added logging to catch any npm install issues
        env:
          CI: false # Sometimes helpful to avoid certain build errors

      - name: Build project
        run: npm run build
        # Added logging to better track potential build errors
        env:
          CI: false

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          BRANCH: gh-pages
          FOLDER: build
