name: CI/CD for food_order frontend project

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Explicitly setting Node 20

      - name: Install dependencies
        run: npm install
        env:
          CI: false # Avoid strict CI checks
        continue-on-error: true # Allows workflow to continue even if npm install fails to show more logs

      - name: Debug: List project structure
        run: ls -la
        # Listing files to ensure everything is in place after the checkout and install

      - name: Build project
        run: npm run build
        env:
          CI: false
        continue-on-error: true # Allows workflow to continue even if build fails for debugging

      - name: Deploy to Github Pages
        if: success() # Ensure deploy only happens if build succeeds
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          BRANCH: gh-pages
          FOLDER: build
